- name: Run database container
  docker_container:
    name: db
    image: postgres:15
    state: started
    restart_policy: always
    env:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: db
    networks:
      - name: my_app_network_v3
    volumes:
      - db_data:/var/lib/postgresql/data
