version: "3.8"

services:
  backend:
    build: ./DockerfileSimpleApi/simpleapi
    container_name: simpleapi
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - app-network-v2
  database:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network-v2
  httpd:
    build: ./DockerfileHttpServer
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network-v2

networks:
  app-network-v2:
    external: true

volumes:
  db-data:
