name: CI devops 2025

on:
  push:
    branches:
      - main
      - tp1
      - tp2
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: DockerfileSimpleApi/simpleapi # 👈 this line is critical!

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Build and test with Maven
        run: mvn clean verify
